fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.1.1
    hooks:
      - id: clang-format
        args: [--style=Google, -i]
      # - id: cppcheck # Not working -- fails silently, and has issues with includes.
      #  args: [--enable=all, -v,  extensions]
